name: encoding

dependencies:
- base
- rio
- bytestring
- binary
- attoparsec
- conduit
- conduit-extra
- attoparsec-binary
- vector-binary-instances

library:
  source-dirs: src

tests:
  encoding-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - encoding
    - hspec
    - QuickCheck
    - quickcheck-instances
